### ISSUE TITLE
/xlbonus doesn't advertise a clear way to cancel notifications

### ISSUE THREAD

**Issue by ff-meli** [goaaats/Dalamud#20]
From looking through the code, it seems like 'all' might be the intended way to cancel these, but that isn't very intuitive and should be clarified in the help text somewhere if so.

It also looks like the effectively-hidden 'none' option would work but the code makes that seem less intentional.

Either way, the messaging should probably be clarified a bit.

**Comment by goaaats** [comment]
I've added the "none" option to the help text for now.
