### ISSUE TITLE
RTTS (RivaTuner) does not work with XIVLauncher in-game features

### ISSUE THREAD

**Issue by Lani27** [goaaats/Dalamud#61]
**Describe the bug here:**
XIVLauncher plugin GUI not loading with /xlplugins, nor any other plugin command
when RTTS (https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html) is running.

**Steps to reproduce the bug:**
Have RTTS (https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html) running as an overlay, or FPS limiter before launching the game with XIVLauncher

**Expected behavior**
I expected the /xlplugins command to output a GUI, and /pcombo command to output the plugin GUI.

**Other information (*please* complete the following information):**
  Operating System: Windows 10, 2004
  XIVLauncher version: v4.7.12.0
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: XIVCombo 5.2

**Additional information**
When I launch the game with RTTS off and turn it on after the plugins have loaded,  the GUI's load fine.

**Comment by goaaats** [comment]
Hey guys, I'm gonna close this since we decided that we won't fix RivaTuner compatibility for now.
If you are running into this and want to use the in-game features, please use something like NVidias tool.
