### ISSUE TITLE
territory isn't set until you zone somewhere else after login, so it is initially blank and may never be correct

### ISSUE THREAD

**Issue by ff-meli** [goaaats/Dalamud#74]
Somewhat minor issue, but with the change to territory type, the value is now not set until you zone somewhere else from where you logged in.

This mainly affects the RP plugin, but it is kind of unfortunate to have your location be invalid if you happen to stay in town etc.

**Comment by goaaats** [comment]
I went for this because everyone has the plug-in injected when logging in so it shouldn't be an issue, or am I missing something

**Comment by ff-meli** [comment]
I've still gotten this another couple times, but it seems completely inconsistent and pretty minor, and does seem to "usually" work, so it's probably not worth bothering with.
